import { Inter } from "next/font/google"
import Link from "next/link"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ padding: 50 }}>
          <p>Yellow is intercepting route as modal</p>

          <ul>
            {[
              "/intercepting/blue",
              "/intercepting/red",
              "/intercepting/yellow",
            ].map((link) => (
              <li key={link}>
                <Link href={link}>{link}</Link>
              </li>
            ))}
          </ul>
        </div>

        {children}
      </body>
    </html>
  )
}
